sudo: false
language: go
go:
  - "1.9"
  - "1.10"
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - go tool vet .
  - go test -v -race ./...