version: '3'
services:
  mantis-webhook:
    build: .
    depends_on:
      - mantis-webhook-db
    ports:
      - ${APP_PORT}:8080

  mantis-webhook-db:
    image: postgres:alpine
    volumes:
      - ${DATABASE_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: mantis-webhook-db
    ports:
      - '5432:5432'